Biluthyrning/Models/User.cs
using System.ComponentModel;

namespace Biluthyrning.Models
{
	public class User
	{
		public int UserId { get; set; }
		public bool Blacklist { get; set; }
		public bool IsAdmin { get; set; }
        [DisplayName("Förnamn")]
        public string FirstName { get; set; } = "";
        [DisplayName("Efternamn")]
        public string LastName { get; set; } = "";
        [DisplayName("Mailadress")]
        public string Email { get; set; } = "";
        [DisplayName("Telefonnummer")]
        public string PhoneNumber { get; set; } = "";
	}
}

Biluthyrning/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Biluthyrning.Data;
using Biluthyrning.Models;

namespace Biluthyrning.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICar carRepository;

        public CarsController(ICar carRepository)
        {
            this.carRepository = carRepository;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            return carRepository != null ?
                        View(await carRepository.GetAllAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Cars'  is null.");
        }
        // GET: Cars/OurCars
        public async Task<IActionResult> OurCars()
        {
            return carRepository != null ?
                        View(await carRepository.GetAllAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Cars'  is null.");
        }


        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null || carRepository == null)
            {
                return NotFound();
            }

            var car = await carRepository.GetByIdAsync(id);//Det här kan väl inte bli bra?

            /* .FirstOrDefaultAsync(m => m.Id == id);*/
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            List<SelectListItem> gear = new()
            {
                new SelectListItem { Value = "Manuell", Text = "Manuell" },
                new SelectListItem { Value = "Automatisk", Text = "Automatisk" },
                
            };
            ViewBag.Gear = gear;


            List<SelectListItem> fuel = new()
            {
                new SelectListItem { Value = "Bensin", Text = "Bensin" },
                new SelectListItem { Value = "Diesel", Text = "Diesel" },
                new SelectListItem { Value = "Elektrisk", Text = "Elektrisk" }
            };
            ViewBag.Fuel = fuel;

            List<SelectListItem> size = new()
            {
                new SelectListItem { Value = "Liten", Text = "Liten" },
                new SelectListItem { Value = "Mellan", Text = "Mellan" },
                new SelectListItem { Value = "Stor", Text = "Stor" }
            };
            ViewBag.Size = size;

            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarId,Name,Brand,Color,Gear,FuelType,Size,Price")] Car car)
        {
            if (ModelState.IsValid)
            {
                await carRepository.CreateAsync(car);
                //await carRepository.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            List<SelectListItem> gear = new()
            {
                new SelectListItem { Value = "Manuell", Text = "Manuell" },
                new SelectListItem { Value = "Automatisk", Text = "Automatisk" },

            };
            ViewBag.Gear = gear;

            List<SelectListItem> fuel = new()
            {
                new SelectListItem { Value = "Bensin", Text = "Bensin" },
                new SelectListItem { Value = "Diesel", Text = "Diesel" },
                new SelectListItem { Value = "Elektrisk", Text = "Elektrisk" }
            };
            ViewBag.Fuel = fuel;

            List<SelectListItem> size = new()
            {
                new SelectListItem { Value = "Liten", Text = "Liten" },
                new SelectListItem { Value = "Mellan", Text = "Mellan" },
                new SelectListItem { Value = "Stor", Text = "Stor" }
            };
            ViewBag.Size = size;

            if (id == null || carRepository == null)
            {
                return NotFound();
            }

            var car = await carRepository.GetByIdAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarId,Name,Brand,Color,Gear,FuelType,Size,Price")] Car car)
        {
            if (id != car.CarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                await carRepository.UpdateAsync(car);
                
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || carRepository == null)
            {
                return NotFound();
            }

            var car = await carRepository.GetByIdAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (carRepository == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Cars'  is null.");
            }
            var car = await carRepository.GetByIdAsync(id);
            if (car != null)
            {
                await carRepository.DeleteAsync(id);
            }
            return RedirectToAction(nameof(Index));
        }

        
    }
}

Biluthyrning/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Biluthyrning.Data;
using Biluthyrning.Models;
using Biluthyrning.ViewModels;
using Microsoft.Extensions.Hosting;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;

namespace Biluthyrning.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUser userRepository;
        private readonly ICar carRepository;
        private readonly IBooking bookingRepository;

        public UsersController(IUser userRepository, ICar carRepository, IBooking bookingRepository)
        {
            this.userRepository = userRepository;
            this.carRepository = carRepository;
            this.bookingRepository = bookingRepository;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return userRepository != null ?
                        View(await userRepository.GetAllAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Users'  is null.");
        }
        // GET: Users/UserView
        public async Task<IActionResult> UserView()
        {
            ViewBag.Users = new SelectList(await userRepository.GetAllAsync(), "UserId", "FirstName");


            return View();

        }


        //GET:Users/AdminLista
        public async Task<IActionResult> AdminView()
        {
                return View();
        }

        //GET:Users/UserCreate
        public async Task<IActionResult> UserCreate()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserCreate([Bind("UserId,Blacklist,IsAdmin,FirstName,LastName,Email,PhoneNumber")] User user)
        {
            if (ModelState.IsValid)
            {
                await userRepository.CreateAsync(user);

                return RedirectToAction("UserView");
            }
            return View(user);
        }

        //GET:Users/AdminLista
        public async Task<IActionResult> AdminLista()
        {
            var hej = await bookingRepository.GetAllAsync();
            var car = new List<RentedCarsViewModel>();
            foreach (var item in hej)
            {
                var c = new RentedCarsViewModel();
                c.CarId = item.CarId;
                var x=carRepository.GetByIdAsync(item.CarId).Result.Name;
                c.Name = x;
                c.Start = item.Start;
                c.End = item.End;
                c.FirstName = userRepository.GetByIdAsync(item.UserId).Result.FirstName;
                c.LastName = userRepository.GetByIdAsync(item.UserId).Result.LastName;
                car.Add(c);
            }
            return View(car);
        }

        //GET: Users/AdminListaFiltered
        public async Task<IActionResult> AdminListaFiltered(DateTime startDate, DateTime endDate)
        {
            var car = new List<RentedCarsViewModel>();
            foreach (var item in await bookingRepository.GetAllAsync())
            {
                if ((startDate >= item.Start && startDate <= item.End) || (endDate >= item.Start && endDate <= item.End))
                {
                    if (endDate >= item.Start)
                    {
                        var c = new RentedCarsViewModel();
                        c.CarId = item.CarId;
                        c.Start = item.Start;
                        c.End = item.End;
                        c.FirstName = userRepository.GetByIdAsync(item.UserId).Result.FirstName;
                        c.LastName = userRepository.GetByIdAsync(item.UserId).Result.LastName;
                        car.Add(c);
                    }
                }
            }
            return View(car);
        }

        //GET: Users/DetailsAdminView
        public async Task<IActionResult> DetailsAdminView(int id)
        {
            return View(await userRepository.GetByIdAsync(id));
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var userscar = new List<DetailsUserViewModel>();
            foreach (var item in await bookingRepository.GetByUserIdAsync(id))
            {
                var c = new DetailsUserViewModel();
                c.Booking = item;
                c.Car = await carRepository.GetByIdAsync(item.CarId);
                c.User = await userRepository.GetByIdAsync(item.UserId);
               
                userscar.Add(c);
            }
            //ViewBag.UserDetails=  (await userRepository.GetAllAsync(), "UserId", "FirstName", "LastName", "Email", "PhoneNumber");
            return View(userscar);
        }

        // GET: Users/DetailsViewUser/5
        public async Task<IActionResult> DetailsViewUser(int userid, int id)
        {
            if (userid == null || userRepository == null)
            {
                return NotFound();
            }
            if (userid > id)
            {
                id = userid;
            }
            if (id > userid)
            {
                userid = id;
            }
            var user = await userRepository
                .GetByIdAsync(userid);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Blacklist,IsAdmin,FirstName,LastName,Email,PhoneNumber")] User user)
        {
            if (ModelState.IsValid)
            {
                await userRepository.CreateAsync(user);

                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || userRepository == null)
            {
                return NotFound();
            }

            var user = await userRepository.GetByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // GET: Users/EditViewUser/5
        public async Task<IActionResult> EditViewUser(int id)
        {
            if (id == null || userRepository == null)
            {
                return NotFound();
            }

            var user = await userRepository.GetByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

    

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Blacklist,IsAdmin,FirstName,LastName,Email,PhoneNumber")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await userRepository.UpdateAsync(user);

                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }
        // POST: Users/EditViewUser/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditViewUser(int id, [Bind("UserId,Blacklist,IsAdmin,FirstName,LastName,Email,PhoneNumber")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await userRepository.UpdateAsync(user);
                
                TempData["successMessage"] = "Din information har sparats";
                return RedirectToAction("EditViewUser");
            }
            return View(user);
        }
        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || userRepository == null)
            {
                return NotFound();
            }

            var user = await userRepository
                .GetByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (userRepository == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Users'  is null.");
            }
            var user = await userRepository.GetByIdAsync(id);
            if (user != null)
            {
                await userRepository.DeleteAsync(id);
            }

            //await userRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Biluthyrning/Views/Users/AdminLista.cshtml
@model IEnumerable<Biluthyrning.ViewModels.RentedCarsViewModel>
<script src="https://kit.fontawesome.com/8ff6b8bfa7.js" crossorigin="anonymous"></script>
@{
	ViewData["Title"] = "Bokningar";
}

<div class="text-center">
	<h1 class="display-4 text-black">Bokningar</h1>
</div>


<p class="text-center">
	<a asp-controller="Bookings" asp-action="CreateAdmin" class="btn btn-primary">Skapa ny</a>
	<a class="btn btn-primary" asp-controller="Bookings" asp-action="FilterList">Filtrera Bokningar</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.CarId)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.FirstName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.LastName)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Start)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.End)
			</th>

			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.CarId)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.FirstName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.LastName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Start)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.End)
				</td>

				<td>
					<a asp-controller="Bookings" asp-action="Edit" asp-route-id="@item.CarId"><i class="fa-solid fa-pen-to-square" style="color: #000066;"></i></a> |
					<a asp-controller="Bookings" asp-action="DeleteBooking" asp-route-id="@item.CarId"><i class="fa-solid fa-trash" style="color: #000066;"></i></a>
				</td>
			</tr>
		}
	</tbody>
</table>

Biluthyrning/Views/Users/AdminListaFiltered.cshtml
@model IEnumerable<Biluthyrning.ViewModels.RentedCarsViewModel>
<script src="https://kit.fontawesome.com/8ff6b8bfa7.js" crossorigin="anonymous"></script>
@{
    ViewData["Title"] = "AdminListaFiltered";
}

<h1>AdminLista</h1>

<p>
    <a asp-controller="Bookings" asp-action="CreateAdmin" class="btn btn-primary">Skapa ny</a> | 
    <a asp-controller="Bookings" asp-action="FilterList" class="btn btn-primary">Filtrera Bokningar</a> | 
    <a asp-controller="Users" asp-action="AdminLista" class="btn btn-secondary">Tillbaka</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CarId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.End)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CarId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.End)
            </td>
           
            <td>
                    <a asp-controller="Bookings" asp-action="Edit" asp-route-id="@item.CarId"><i class="fa-solid fa-pen-to-square" style="color: #000066;"></i></a> |
                    <a asp-controller="Bookings" asp-action="Details" asp-route-id="@item.CarId"><i class="fa-solid fa-circle-info" style="color: #000066;"></i></a> |
                    <a asp-controller="Bookings" asp-action="Delete" asp-route-id="@item.CarId"><i class="fa-solid fa-trash" style="color: #000066;"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

Biluthyrning/Views/Users/AdminView.cshtml
@model Biluthyrning.Models.User

@{
    ViewData["Title"] = "AdminView";
}

<div class="text-center">
    <h1 class="display-4 text-black">👀Välkommen Admin👀</h1>
 
<a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">👉 Redigera Användare 👈</a>
    <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">👉 Redigera Bilar 👈</a>
    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="AdminLista">👉 Bokningar 👈</a>
    <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Booking">👉 Tillgänliga Bilar 👈</a>

</div>

Biluthyrning/Views/Users/Create.cshtml
@model Biluthyrning.Models.User

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Blacklist" /> @Html.DisplayNameFor(model => model.Blacklist)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
				<input type="submit" value="Skapa" class="btn btn-primary" /> | <a class="btn btn-primary" asp-action="Index">Tillbaka</a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Biluthyrning/Views/Users/Delete.cshtml
@model Biluthyrning.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Blacklist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Blacklist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="submit" value="Radera" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Tillbaka</a>
    </form>
</div>

Biluthyrning/Views/Users/Details.cshtml
@model IEnumerable<Biluthyrning.ViewModels.DetailsUserViewModel>
<script src="https://kit.fontawesome.com/8ff6b8bfa7.js" crossorigin="anonymous"></script>

@{
    ViewData["Title"] = "Details";
}


<h1>Mina bokningar</h1>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Car.CarId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Car.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Car.Brand)
                </th>    
                <th>
                    @Html.DisplayNameFor(model => model.Car.Color)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Car.Gear)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Car.FuelType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Car.Size)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Car.Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Car.CarId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Car.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Car.Brand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Car.Color)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Car.Gear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Car.FuelType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Car.Size)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Car.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Booking.Start)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Booking.End)
                    </td>
                    <td>


                        <a asp-controller="Bookings" asp-action="Delete" asp-route-id="@item.Booking.Id"><i class="fa-solid fa-trash" style="color: #000066;"></i></a>
                    </td>
                </tr>
            }
</div>
    </tbody>
</table>

Biluthyrning/Views/Users/DetailsAdminView.cshtml
@model Biluthyrning.Models.User

@{
    ViewData["Title"] = "DetailsAdminView";
}


<div class="text-center">
    <h1 class="display-4 text-black">Användare</h1>
</div>



<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Blacklist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Blacklist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.UserId" class="btn btn-primary">Ändra</a> |
    <a asp-action="Index" class="btn btn-secondary">Tillbaka</a>
</div>