Biluthyrning/Models/Booking.cs
using Microsoft.EntityFrameworkCore.Metadata;
using System.ComponentModel;

namespace Biluthyrning.Models
{
	public class Booking
	{
		public int Id { get; set; }
		[DisplayName("Registreringsnummer")]
        public int CarId { get; set; }
      
        public int UserId { get; set; }
        [DisplayName("Startdatum")]
        public DateTime Start { get; set; }
        [DisplayName("Slutdatum")]
        public DateTime End { get; set; }
	}
}

Biluthyrning/ViewModels/AvailableCarsViewModel.cs
using Biluthyrning.Models;

namespace Biluthyrning.ViewModels
{
    public class AvailableCarsViewModel
    {
        public int Id { get; set; }
        public Booking Booking { get; set; }
        public Car Car { get; set; }

    }
}

Biluthyrning/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Biluthyrning.Data;
using Biluthyrning.Models;
using Biluthyrning.ViewModels;
using System.Drawing;
using System.Runtime.ConstrainedExecution;

namespace Biluthyrning.Controllers
{
	public class BookingsController : Controller
	{
		private readonly IBooking bookingRepository;
		private readonly ICar carRepository;
		private readonly IUser userRepository;

		public BookingsController(IBooking bookingRepository, ICar carRepository, IUser userRepository)
		{
			this.bookingRepository = bookingRepository;
			this.carRepository = carRepository;
			this.userRepository = userRepository;
		}

		// GET: Bookings
		public async Task<IActionResult> Index()
		{
			return View(await bookingRepository.GetAllAsync());

		}

		// GET: Bookings/Booking
		public async Task<IActionResult> Booking()
		{
			return View();
		}



        // GET: Cars/BookingCarFirstView
        public async Task<IActionResult> BookingCarFirstView()

        {

            List<SelectListItem> carGear = new()
            { new SelectListItem { Value = "Automatisk", Text = "Automatisk"},
                new SelectListItem { Value = "Manuell", Text = "Manuell"}  };

            List<SelectListItem> carFuel = new()
            {
                new SelectListItem { Value = "Bensin", Text = "Bensin" },
                new SelectListItem { Value = "Diesel", Text = "Diesel" },
                new SelectListItem { Value = "El", Text = "El" }
            };

            List<SelectListItem> carSize = new()
            {
                new SelectListItem { Value = "Liten", Text = "Liten" },
                new SelectListItem { Value = "Mellan", Text = "Mellan" },
                new SelectListItem { Value = "Stor", Text = "Stor" }
            };

            ViewBag.CarGear = carGear;
            ViewBag.Fuel = carFuel;
            ViewBag.CarSize = carSize;

            return View();
        }

        public async Task<IActionResult> FilterList()
        {
            return View();
        }

        // GET: Bookings/AvailableCars

        public async Task<IActionResult> AvailableCars(SearchCarViewModel searchCarViewModel)

        {
            var availableCarsVM = new List<AvailableCarsViewModel>();
            foreach (var c in await carRepository.GetAllAsync())
            {
                var post = new AvailableCarsViewModel();
                post.Car = c;
                post.Booking = await bookingRepository.GetByCarIdAsync(c.CarId);
                if (searchCarViewModel.Car == null && post.Booking != null)
                {
                    if ((searchCarViewModel.DatePicker.StartDate >= post.Booking.End && searchCarViewModel.DatePicker.EndDate >= post.Booking.End) ||
                         (searchCarViewModel.DatePicker.EndDate <= post.Booking.Start && searchCarViewModel.DatePicker.StartDate <= post.Booking.Start))
                    {
                        availableCarsVM.Add(post);
                    }
                }
                else if (searchCarViewModel.Car == null && post.Booking == null)
                {
                    {
                        availableCarsVM.Add(post);
                    }
                }
                else if (post.Booking != null)
                {
                    if (((searchCarViewModel.DatePicker.StartDate >= post.Booking.End && searchCarViewModel.DatePicker.EndDate >= post.Booking.End) ||
                        (searchCarViewModel.DatePicker.EndDate <= post.Booking.Start && searchCarViewModel.DatePicker.StartDate <= post.Booking.Start)) &&
                        post.Car.Gear == searchCarViewModel.Car.Gear && post.Car.FuelType == searchCarViewModel.Car.FuelType && post.Car.Size == searchCarViewModel.Car.Size)
                    {
                        availableCarsVM.Add(post);
                    }
                }
                else if (searchCarViewModel.Car != null)
                {
                    if (post.Car.Gear == searchCarViewModel.Car.Gear && post.Car.FuelType == searchCarViewModel.Car.FuelType && post.Car.Size == searchCarViewModel.Car.Size)
                    {
                        availableCarsVM.Add(post);
						
					}
                }
            }
        
            
            
                return View(availableCarsVM);
            
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int id)
        {
            return View(await bookingRepository.GetByIdAsync(id));
        }

        // GET: Bookings/Create
        public async Task<IActionResult> CreateAsync(int id)
        {
            ViewBag.Users = new SelectList(await userRepository.GetAllAsync(), "UserId", "FirstName");
            var model = new Booking { CarId = id, Start = DateTime.Today, End = DateTime.Today };
            return View(model);
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CarId,UserId,Start,End")] Booking booking)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var bookCar =
                    await bookingRepository.GetByCarIdAsync(booking.CarId);
                    if (bookCar == null)
                    {
                        await bookingRepository.CreateAsync(booking);
                        return RedirectToAction(nameof(ConfirmedBooking));
                    }
                    if ((booking.Start >= bookCar.End && booking.End >= bookCar.End) ||
                    (booking.End <= bookCar.Start && booking.Start <= bookCar.Start))
                    {
                        await bookingRepository.CreateAsync(booking);
                        return RedirectToAction(nameof(ConfirmedBooking));
                    }
					 return View();
				
				}
         
            }
            catch
            {
				
			}
            return View();
        }


        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || bookingRepository.GetAllAsync == null)
            {
                return NotFound();
            }

            var booking = await bookingRepository.GetByIdAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int CarId, int UserId, DateTime Start, DateTime End, Booking booking)
        {
            if (id != booking.Id)
                return NotFound();

			if (ModelState.IsValid)
			{
				try
				{
					var b = await bookingRepository.GetByIdAsync(id);
					b.UserId = booking.UserId;
					b.CarId = booking.CarId;
					b.Start = booking.Start;
					b.End = booking.End;
					await bookingRepository.UpdateAsync(b);
				}
				catch (Exception)
				{
					return View();
				}
				//return RedirectToAction(nameof(Index));
				return RedirectToAction("AdminLista", "Users");

			}
			return View(booking);
		}

		// GET: Bookings/Delete/5
		public async Task<IActionResult> Delete(int id)
		{


			var d = new DetailsUserViewModel();
			d.Booking = await bookingRepository.GetByIdAsync(id);
			d.Car = await carRepository.GetByIdAsync(d.Booking.CarId);
			d.User = await userRepository.GetByIdAsync(d.Booking.UserId);



			return View(d);

		}

		// POST: Bookings/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var booking = await bookingRepository.GetByIdAsync(id);
			if (ModelState.IsValid)
			{
				try
				{
					await bookingRepository.DeleteAsync(id);
				}
				catch (Exception)
				{
					return View();
				}
				return RedirectToAction("Details", "Users", new { id = booking.UserId });
			}
			return View(booking);

		}
		// GET: Bookings/ConfirmedBooking/5
		public async Task<IActionResult> ConfirmedBooking()
		{

			return View();
		}

		// GET: Bookings/DeleteBooking/5
		public async Task<IActionResult> DeleteBooking(int id)
		{


			var d = new DetailsUserViewModel();
			d.Booking = await bookingRepository.GetByIdAsync(id);
			d.Car = await carRepository.GetByIdAsync(d.Booking.CarId);
			d.User = await userRepository.GetByIdAsync(d.Booking.UserId);



			return View(d);

		}

		// POST: Bookings/DeleteBooking/5
		[HttpPost, ActionName("DeleteBooking")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteBookings(int id)
		{
			var booking = await bookingRepository.GetByIdAsync(id);
			if (ModelState.IsValid)
			{
				try
				{
					await bookingRepository.DeleteAsync(id);
				}
				catch (Exception)
				{
					return View();
				}
				return RedirectToAction("AdminLista", "Users");
			}
			return View(booking);

		}


	}
}

Biluthyrning/Views/Bookings/AvailableCars.cshtml
@model List<Biluthyrning.ViewModels.AvailableCarsViewModel>

@{
	ViewData["Title"] = "Available Cars";
}


<div class="text-center">
	<h1 class="display-4 text-black">Tillgänliga bilar</h1>
</div>


<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model[0].Car.CarId)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Car.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Car.Brand)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Car.Color)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Car.Gear)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Car.FuelType)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Car.Size)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Car.Price)
			</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		@if (Model.Count != 0)
		{


			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Car.CarId)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Car.Name)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Car.Brand)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Car.Color)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Car.Gear)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Car.FuelType)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Car.Size)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Car.Price)
					</td>
					<td>
						<a asp-action="Create" asp-route-id="@item.Car.CarId" button class="btn btn-primary" type="submit" value="Create">Boka</a>
					</td>
				</tr>
			}
		}
		else
		{
			<p>
				Tyvärr finns inga bilar med dina önskemål inom ditt datumspann.
			</p>
		}

		</div>
		@section Scripts {
			@{
				await Html.RenderPartialAsync("_ValidationScriptsPartial");
			}
		}
	</tbody>
</table>

Biluthyrning/Views/Bookings/Booking.cshtml
@model Biluthyrning.ViewModels.SearchCarViewModel
@{
    ViewBag.Title = "BokaBilTest";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="AvailableCars">  
            <h1>
                När vill du hyra bil?
            </h1>
        <div class="form-group">
                <label asp-for="DatePicker.StartDate" class="control-label"></label>
                <input asp-for="DatePicker.StartDate" class="form-control" />
                <span asp-validation-for="DatePicker.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePicker.EndDate" class="control-label"></label>
                <input asp-for="DatePicker.EndDate" class="form-control" />
                <span asp-validation-for="DatePicker.EndDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
             <button class="btn btn-primary" type="submit" value="Create">Se tillgängliga bilar</button>
                <a class="btn btn-primary" type="submit" asp-area="" asp-controller="Bookings" asp-action="BookingCarFirstView"> Avancerad sök </a>


            </div>
        </form>
    </div>
</div>

Biluthyrning/Views/Bookings/BookingCarFirstView.cshtml
@model Biluthyrning.ViewModels.SearchCarViewModel

@{
	ViewData["Title"] = "BookingCarFirstView";

}

<h1>Bilval</h1>
<h4>Gör dina val:</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="AvailableCars">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Car.Gear" class="control-label"></label>
				<select class="form-select" asp-for="Car.Gear" class="form-control" asp-items="ViewBag.CarGear">
					<option value="none" selected disabled hidden>---Välj växeltyp---</option>
				</select>
				<span asp-validation-for="Car.Gear" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Car.FuelType" class="control-label"></label>
				<select class="form-select" asp-for="Car.FuelType" class="form-control" asp-items="ViewBag.Fuel">
					<option value="none" selected disabled hidden>---Välj drivmedel---</option>
				</select>
				<span asp-validation-for="Car.FuelType" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Car.Size" class="control-label"></label>
				<select class="form-select" asp-for="Car.Size" class="form-control" asp-items="ViewBag.CarSize">
					<option value="none" selected disabled hidden>---Välj storlek---</option>
				</select>
				<span asp-validation-for="Car.Size" class="text-danger"></span>
			</div>
			<h4>Välj datum:</h4>
			<div class="form-group">
				<label asp-for="DatePicker.StartDate" class="control-label"></label>
				<input asp-for="DatePicker.StartDate" class="form-control" />
				<span asp-validation-for="DatePicker.StartDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="DatePicker.EndDate" class="control-label"></label>
				<input asp-for="DatePicker.EndDate" class="form-control" />
				<span asp-validation-for="DatePicker.EndDate" class="text-danger"></span>
			</div>
			<br />
			<br />
			<div class="form-group">
				<button class="btn btn-primary" type="submit" value="Create">Se tillgängliga bilar</button>
			</div>
		</form>
	</div>
</div>

<div class="fade-in-text">
	@TempData["successMessage"]
</div>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
		}

Biluthyrning/Views/Bookings/ConfirmedBooking.cshtml
@model Biluthyrning.Models.Booking

@{
    ViewData["Title"] = "ConfirmedBooking";
}

<h1>Din bokning har nu genomförts!</h1>

<div>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Tillbaka till startsidan</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Biluthyrning/Views/Bookings/Create.cshtml
@model Biluthyrning.Models.Booking

@{
	ViewData["Title"] = "Create";
}

<h1>Boka bil</h1>

<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="CarId" class="control-label"></label>
				<input readonly asp-for="CarId" class="form-control" />
				<span asp-validation-for="CarId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="UserId" class="control-label"></label>
				<select asp-for="UserId" class="form-control" asp-items="ViewBag.Users"></select>
				<span asp-validation-for="UserId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Start" class="control-label"></label>
				<input asp-for="Start" class="form-control" />
				<span asp-validation-for="Start" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="End" class="control-label"></label>
				<input asp-for="End" class="form-control" />
				<span asp-validation-for="End" class="text-danger"></span>
			</div>
			<br />
			<div class="form-group">
				<button asp-route-id="@Model?.UserId" class="btn btn-primary" type="submit" value="Create">Boka</button>
				<a asp-action="BookingCarFirstView" class="btn btn-primary" type="submit">Tillbaka till listan</a>
			</div>
		</form>
	</div>
</div>
@*<div class="fade-in-text">
	@TempData["successMessage"]

</div>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
		}*@

Biluthyrning/Views/Bookings/CreateAdmin.cshtml
@model Biluthyrning.Models.Booking

@{
	ViewData["Title"] = "Create";
}

<h1>Boka bil</h1>

<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="CarId" class="control-label"></label>
				<select asp-for="CarId" class="form-control" asp-items="ViewBag.Cars"></select>
				<span asp-validation-for="CarId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="UserId" class="control-label"></label>
				<select asp-for="UserId" class="form-control" asp-items="ViewBag.Users"></select>
				<span asp-validation-for="UserId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Start" class="control-label"></label>
				<input asp-for="Start" class="form-control" />
				<span asp-validation-for="Start" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="End" class="control-label"></label>
				<input asp-for="End" class="form-control" />
				<span asp-validation-for="End" class="text-danger"></span>
			</div>
			<br />
			<div class="form-group">
				<button asp-route-id="@Model?.UserId" class="btn btn-primary" type="submit" value="Create">Boka</button>
				<a asp-action="BookingCarFirstView" class="btn btn-primary" type="submit">Tillbaka till listan</a>
			</div>
		</form>
	</div>
</div>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Biluthyrning/Views/Bookings/Delete.cshtml
@model Biluthyrning.ViewModels.DetailsUserViewModel


@{
    ViewData["Title"] = "Delete";
}
<h1>Ta bort bokning</h1>

<h3>Är du säker på att du vill ta bort den här heta bokningen?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Car.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Brand)
        </dd>
 
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Car.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Name)
        </dd>
    
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Start)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Start)
        </dd>
      
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.End)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.End)
        </dd>

    </dl>



    <form asp-action="Delete">
        <input type="hidden" asp-for="Booking.Id" />
        <input type="submit" value="Ta bort" class="btn btn-danger" /> |
        <a asp-controller="Users" asp-action="Details" asp-route-id="@Model?.User.UserId" class="btn btn-secondary">Tillbaka</a>

    </form>
</div>

Biluthyrning/Views/Bookings/DeleteBooking.cshtml
@model Biluthyrning.ViewModels.DetailsUserViewModel


@{
    ViewData["Title"] = "DeleteBooking";
}
<h1>Ta bort bokning</h1>

<h3>Är du säker på att du vill ta bort den här heta bokningen?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Car.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Brand)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Car.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Start)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Start)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.End)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.End)
        </dd>

    </dl>



    <form asp-action="DeleteBooking">
        <input type="hidden" asp-for="Booking.Id" />
        <input type="submit" value="Ta bort" class="btn btn-danger" /> |
        <a asp-controller="Users" asp-action="AdminLista" class="btn btn-secondary">Tillbaka</a>

    </form>
</div>

Biluthyrning/Views/Bookings/DeleteDetailsUserViewModel.cshtml
@model Biluthyrning.ViewModels.DetailsUserViewModel


@{
    ViewData["Title"] = "Delete";
}

<h1>Ta bort bokning</h1>

<h3>Är du säker på att du vill ta bort den här heta bokningen?</h3>
<div>
    <h4>Bokning</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Car.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Car.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Brand)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Start)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Start)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.End)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.End)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Booking.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details" asp-controller="Users"asp-route="@Model?User.UserId" class="btn btn-secondary">Tillbaka</a>

    </form>
</div>

Biluthyrning/Views/Bookings/Details.cshtml
@model Biluthyrning.Models.Booking

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Start)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Start)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.End)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.End)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Biluthyrning/Views/Bookings/Edit.cshtml
@model Biluthyrning.Models.Booking

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Booking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CarId" class="control-label"></label>
                <input asp-for="CarId" class="form-control" />
                <span asp-validation-for="CarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Start" class="control-label"></label>
                <input asp-for="Start" class="form-control" />
                <span asp-validation-for="Start" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="End" class="control-label"></label>
                <input asp-for="End" class="form-control" />
                <span asp-validation-for="End" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" /> |
                <a asp-controller="Users" asp-action="AdminLista" class="btn btn-secondary">Tillbaka</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Biluthyrning/Views/Bookings/FilterList.cshtml
@model DatePicker
@{
	ViewBag.Title = "FilterList";
}
<div class="row">
	<div class="col-md-4">
		<form asp-controller="Users" asp-action="AdminListaFiltered">
			<div class="form-group">
				<label asp-for="StartDate" class="control-label"></label>
				<input asp-for="StartDate" class="form-control" />
				<span asp-validation-for="StartDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="EndDate" class="control-label"></label>
				<input asp-for="EndDate" class="form-control" />
				<span asp-validation-for="EndDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Sortera" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

Biluthyrning/Views/Bookings/Index.cshtml
@model IEnumerable<Biluthyrning.Models.Booking>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CarId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.End)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CarId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Start)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.End)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>